dist: xenial
sudo: required

language: python
python:
  - 3.6
  - 3.7
node_js: '8'

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libimage-exiftool-perl
  - pip install -U tox-travis
  - pip install python-coveralls
  - poetry run pre-commit install

script:
  - poetry run pre-commit run -a
  - tox -r

after_success:
  - coveralls

notifications:
  email: false
