language: python

python:
  - 3.6

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libimage-exiftool-perl
  - pip install -U tox
  - pip install python-coveralls

script:
  - tox -r

after_success:
  - coveralls

notifications:
  email: false
